name: Django CI

on:
  push:
    branches: [ dev ]
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
     
        # Runs a single command using the runners shell
    - name: Executing remote commands via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASS }}
        script: |
          cd /var/www/zc_plugin_company_sales_prospect
          git checkout dev
          git stash
          git pull
          pip install -r requirements.txt
          cd react-spa/epictetus
          yarn install
          yarn build
          cd ../../frontend/epictetus
          yarn install
          yarn build

          python manage.py migrate
          python manage.py runserver
          #- name: Run Tests
          #run: |
          #python manage.py test
