name: Company sales Deployment Pipeline

on:
  # Triggers the workflow on push or pull request events but for the dev branch
  push:
    branches: [dev]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  deploy:
    

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      - name: Install yarn dependencies and build react-spa project
        run: |
          cd frontend/mainApp/
          yarn install
          yarn build
          cd ../../frontend/rootApp
          yarn install
          yarn build
 
      - name: Copy Root dist folder to server
        uses: Creepios/sftp-action@v1.0.1
        with:
          password: ${{ secrets.SSH_PASS }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          localPath: './frontend/rootApp/dist/'
          remotePath: '/var/www/zc_plugin_company_sales_prospect/backend/build/root/'

      - name: Copy Epictetus dist folder to server
        uses: Creepios/sftp-action@v1.0.1
        with:
          password: ${{ secrets.SSH_PASS }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          localPath: './frontend/mainApp/dist/'
          remotePath: '/var/www/zc_plugin_company_sales_prospect/backend/build/main/'


      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          password: ${{ secrets.SSH_PASS }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          script: |
            cd /var/www/zc_plugin_company_sales_prospect/
            git checkout dev
            git stash
            git pull origin dev
            cd backend
            pip install -r requirements.txt
            python manage.py collectstatic --noinput
            cd ../frontend/rootApp
            yarn install
            cd ../../frontend/mainApp
            yarn install
            #systemctl daemon-reload
      
